### ISSUE TITLE
KeyError: 'included_domains'

### ISSUE THREAD

**Issue by mvenus2** [Hassassistant/OpenAssist#2]
Logger: homeassistant.setup
Source: setup.py:396
First occurred: 1:51:40 PM (1 occurrences)
Last logged: 1:51:40 PM

Unable to prepare setup for platform openassist.sensor: Unable to set up component.

2023-06-11 13:51:40.505 ERROR (MainThread) [homeassistant.setup] Error during setup of component openassist
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 286, in _async_setup_component
result = await task
^^^^^^^^^^
File "/config/custom_components/openassist/__init__.py", line 88, in async_setup
included_domains = [domain.strip() for domain in conf['included_domains'].split(',')]
~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'included_domains'

**Comment by mvenus2** [comment]
Fixed by including "included_domains" in config
